from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal

Status = Literal["ok", "blocked", "error"]
Mode = Literal["TEST", "DRY_RUN", "LIVE"]
Network = Literal["OFF", "ON"]


@dataclass
class ArtifactRef:
    """Reference to an artifact generated by an agent."""
    path: str
    type: str
    sha256: str
    label: str = ""
    size_bytes: int = 0


@dataclass
class AuditEntry:
    """Audit log entry for agent actions."""
    timestamp: str
    action: str
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ErrorEntry:
    """Error information."""
    code: str
    message: str
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentResult:
    """Standard result schema for agent execution."""
    agent_name: str
    agent_version: str
    run_id: str
    status: Status
    data: Dict[str, Any]
    artifacts: List[ArtifactRef] = field(default_factory=list)
    metrics: Dict[str, Any] = field(default_factory=dict)
    audit: List[AuditEntry] = field(default_factory=list)
    errors: List[ErrorEntry] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "agent_name": self.agent_name,
            "agent_version": self.agent_version,
            "run_id": self.run_id,
            "status": self.status,
            "data": self.data,
            "artifacts": [
                {
                    "path": a.path,
                    "type": a.type,
                    "sha256": a.sha256,
                    "label": a.label,
                    "size_bytes": a.size_bytes,
                }
                for a in self.artifacts
            ],
            "metrics": self.metrics,
            "audit": [
                {
                    "timestamp": e.timestamp,
                    "action": e.action,
                    "details": e.details,
                }
                for e in self.audit
            ],
            "errors": [
                {
                    "code": e.code,
                    "message": e.message,
                    "details": e.details,
                }
                for e in self.errors
            ],
        }


@dataclass
class AgentPayload:
    """Input payload for agent execution."""
    request_id: str
    params: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
